package com.puresound.backend.constant.api;

public enum ApiMessage {
    GET_LISTENER_SUCCESS,
    INVALID_REQUEST, MISMATCH_REQUEST, LOGIN_WRONG_INFO, SYSTEM_RESOURCE_NOT_FOUND, LISTENER_NOT_FOUND, UNKNOWN_USER_TYPE, INTERNAL_SERVER_ERROR
}
